import { expect, test } from './network-changed-fixture';

test('Full HD Build shows authored station and bench thumbnails with accessible keyboard selection',async({page},info)=>{
  await page.setViewportSize({width:1920,height:1080});
  await page.goto('/?renderer=oblique');
  await page.getByRole('button',{name:'New prison',exact:true}).click();
  await expect(page.locator('.hud-clock__day')).toHaveText('1');
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByRole('button',{name:'Build',exact:true}).click();
  const list=page.locator('.hud-build__list');
  const ids=await list.locator('[data-buildable]').evaluateAll(rows=>rows.map(row=>(row as HTMLElement).dataset['buildable']!));
  const bench=list.locator('[data-buildable="bench-wooden"]');
  await bench.focus();await page.keyboard.press('Enter');
  await expect(bench).toHaveAttribute('aria-checked','true');
  const benchImage=bench.locator('img.hud-build__object-thumbnail');
  await expect(benchImage).toBeVisible();
  expect(await benchImage.evaluate(image=>(image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({path:info.outputPath('bench-thumbnail-fullhd.png')});
  const footprint=page.locator('.hud-build__selected-footprint');
  await expect(footprint).toHaveText('Occupied squares: 2 \u00d7 1');
  await page.locator('.hud-build__arm').click();
  await page.mouse.move(950,540);
  const target=page.locator('.hud-build__target-value');
  await expect(target).toContainText('2 \u00d7 1 tiles at');
  const anchor=await target.textContent();
  await bench.focus();
  const distance=ids.indexOf('exercise-station')-ids.indexOf('bench-wooden');
  for(let i=0;i<Math.abs(distance);i++)await page.keyboard.press(distance>0?'ArrowDown':'ArrowUp');
  const station=list.locator('[data-buildable="exercise-station"]');
  await expect(station).toBeFocused();await page.keyboard.press('Enter');
  await expect(station).toHaveAttribute('aria-checked','true');
  await expect(station).toContainText('80');
  const stationImage=station.locator('img.hud-build__object-thumbnail');
  await expect(stationImage).toBeVisible();
  expect(await stationImage.evaluate(image=>(image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  expect(await stationImage.getAttribute('src')).not.toBe(await benchImage.getAttribute('src'));
  await expect(stationImage).toHaveAttribute('alt','');
  await expect(station).toHaveAccessibleName(/Exercise station.*80/);
  await expect(station.locator('svg')).toBeHidden();
  await expect(footprint).toHaveText('Occupied squares: 2 \u00d7 1');
  await expect(target).toHaveText(anchor!);
  await page.screenshot({path:info.outputPath('station-thumbnail-fullhd.png')});
  await page.keyboard.press('Escape');
  await expect(page.locator('.hud-build__arm')).toHaveAttribute('data-armed','false');
  await expect(target).toHaveText('Point at the world');
  await page.screenshot({path:info.outputPath('station-escape-fullhd.png')});
});
