import { expect, test } from './network-changed-fixture';
import { installTee, sentCommands } from './playtest-harness';

test('Full HD built room plan fits only on request and camera retains its Save/Load contract', async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  await installTee(page);
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/?oblique-preview=1');
  await page.getByRole('button', { name: 'New prison' }).click();
  await expect(page.locator('body[data-oblique-preview="ready"]')).toBeVisible();
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Room plans', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Room plans' });
  await dialog.getByRole('button', { name: 'Four-cell row' }).click();
  await dialog.getByRole('spinbutton', { name: 'Plan origin X' }).fill('10');
  await dialog.getByRole('spinbutton', { name: 'Plan origin Y' }).fill('10');
  await expect(dialog.getByRole('status')).toContainText('clear');
  const viewport = page.locator('.hud-minimap__viewport');
  const before = await viewport.evaluate((element) => `${element.style.left}/${element.style.top}/${element.style.width}`);
  await dialog.getByRole('button', { name: 'Place room plan' }).click();
  expect((await sentCommands(page)).filter((command) => command.type === 'PlaceRoomTemplate')).toHaveLength(1);
  expect(await viewport.evaluate((element) => `${element.style.left}/${element.style.top}/${element.style.width}`)).toBe(before);
  await dialog.getByRole('button', { name: 'Fit plan in view' }).click();
  await expect(dialog).not.toBeVisible();
  await expect.poll(async () => viewport.evaluate((element) => `${element.style.left}/${element.style.top}/${element.style.width}`)).not.toBe(before);
  const fitted = await viewport.evaluate((element) => `${element.style.left}/${element.style.top}/${element.style.width}`);
  await page.screenshot({ path: testInfo.outputPath('four-cell-row-fit-fullhd.png') });
  await page.getByRole('button', { name: 'Save now' }).click();
  await expect(page.locator('.save-panel__status')).toContainText('Saved (generation ');
  await page.reload();
  await page.locator('.save-panel__item button').filter({ hasText: 'Load' }).first().click();
  await expect(page.locator('body[data-oblique-preview="ready"]')).toBeVisible();
  await expect.poll(async () => viewport.evaluate((element) => `${element.style.left}/${element.style.top}/${element.style.width}`)).not.toBe(fitted);
});
