import { expect, test } from './network-changed-fixture';
import { installTee, sentCommands } from './playtest-harness';

test('Full HD angled mouse Yard is a real reversible zone through Save/Load with no wall order', async ({ page }) => {
  await installTee(page);
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/?renderer=oblique');
  await page.getByRole('button', { name: 'New prison' }).click();
  await expect(page.locator('.hud-clock__day')).toHaveText('1');
  const roomCount = page.locator('[data-metric="rooms"] .ui-stat__value');
  await expect(roomCount).toHaveText('0');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Room plans', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Room plans' });
  await dialog.getByRole('button', { name: 'Yard', exact: true }).click();
  await dialog.getByRole('button', { name: 'Place on map', exact: true }).click();
  await page.mouse.move(880, 380);
  const ghost = page.locator('.room-template-world-ghost');
  await expect(ghost).toHaveAttribute('data-ready', 'clear');
  await expect(ghost.locator('polygon')).toHaveCount(64);
  await page.mouse.down();
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await page.mouse.up();
  expect((await sentCommands(page)).filter(command => command.type === 'PlaceRoomTemplate')).toEqual([]);
  await page.mouse.move(881, 380);
  await expect(ghost).toHaveAttribute('data-ready', 'clear');
  await page.mouse.click(881, 380);
  await expect.poll(async () => (await sentCommands(page)).filter(command => command.type === 'PlaceRoomTemplate').length).toBe(1);
  expect((await sentCommands(page)).filter(command => command.type === 'PlaceBuildOrder')).toEqual([]);
  await page.getByRole('button', { name: 'Play at normal speed', exact: true }).click();
  await expect(roomCount).toHaveText('1');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  const saveLoad = async () => {
    await page.getByRole('button', { name: 'Save now', exact: true }).click();
    await expect(page.locator('.save-panel__status')).toContainText('Saved');
    await page.locator('.save-panel__item').first().getByRole('button', { name: 'Load', exact: true }).click();
    await expect(page.locator('.save-panel__status')).toHaveText('Loaded.');
  };
  await saveLoad();
  await expect(roomCount).toHaveText('1');
  await page.getByRole('button', { name: 'Undo the last placement', exact: true }).click();
  await expect(roomCount).toHaveText('0');
  await saveLoad();
  await expect(roomCount).toHaveText('0');
  await page.getByRole('button', { name: 'Redo the last undone placement', exact: true }).click();
  await page.getByRole('button', { name: 'Play at normal speed', exact: true }).click();
  await expect(roomCount).toHaveText('1');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await saveLoad();
  await expect(roomCount).toHaveText('1');
  expect((await sentCommands(page)).filter(command => command.type === 'PlaceBuildOrder')).toEqual([]);
  await page.screenshot({ path: 'test-results/yard-mouse-redone-loaded-fullhd.png' });
});
