import { describe, expect, it } from 'vitest';
import { computeSaveChecksum } from '../../src/persistence/checksum';
import { migrateSaveEnvelopeV1ToV2, migrateSaveEnvelopeV2ToV3 } from '../../src/persistence/save-migrations';
import {
  SAVE_SCHEMA_VERSION,
  decodeSaveEnvelope,
  type SaveEnvelopeV1,
  type SaveEnvelopeV2,
} from '../../src/persistence/save-schema';
import { restoreSimulationRuntime, type SessionSnapshotBundle } from '../../src/simulation/runtime/restore-session';
import type { JsonValue } from '../../src/shared/json';
import freshPrisonFixture from '../fixtures/persistence/save-v1-fresh-prison.json';
import inProgressFixture from '../fixtures/persistence/save-v1-in-progress.json';

/**
 * Save-schema V2 -> V3 (#70): the payload gains a `simulation` section
 * carrying the twenty-odd subsystems that hold authoritative state.
 *
 * **Where the V2 saves under test come from.** `tests/fixtures/persistence/`
 * holds V1 fixtures only — V2 was the current version until this change, so
 * no V2 save was ever checked in — and adding one now would mean a fixture
 * generated by the very code under test. A genuine V2 envelope is produced
 * instead by running the checked-in, frozen V1 fixtures through the frozen
 * `migrateSaveEnvelopeV1ToV2`. Both inputs to that are historical artefacts
 * this change does not touch, so the V2 saves below are as independent of V3
 * as a checked-in file would be — and `git diff -- tests/fixtures/` stays
 * empty, which is the contract those fixtures exist to enforce.
 */

const V1_FIXTURES = [
  { name: 'fresh prison (no entities section)', fixture: freshPrisonFixture },
  { name: 'in-progress prison (entities section present)', fixture: inProgressFixture },
];

function v2EnvelopeFrom(fixture: unknown): SaveEnvelopeV2 {
  return migrateSaveEnvelopeV1ToV2(fixture as SaveEnvelopeV1);
}

/** A structured clone through JSON — how a save actually reaches `decodeSaveEnvelope` from storage. */
function throughStorage<T>(value: T): unknown {
  return JSON.parse(JSON.stringify(value)) as unknown;
}

describe('save-schema V2 -> V3 migration', () => {
  for (const { name, fixture } of V1_FIXTURES) {
    it(`migrates a real V2 "${name}" save to the current version`, () => {
      const v2 = v2EnvelopeFrom(fixture);
      expect(v2.saveSchemaVersion).toBe(2);

      const result = decodeSaveEnvelope(throughStorage(v2));
      expect(result).toMatchObject({ ok: true, migrated: true });
      if (!result.ok) return;

      expect(result.value.saveSchemaVersion).toBe(SAVE_SCHEMA_VERSION);
      // Every V2 field crosses untouched: V3 added a section beside them.
      expect(result.value.payload.kernel).toEqual(v2.payload.kernel);
      expect(result.value.payload.world).toEqual(v2.payload.world);
      expect(result.value.payload.construction).toEqual(v2.payload.construction);
      expect(result.value.payload.entities).toEqual(v2.payload.entities);
      expect(result.value.gameVersion).toBe(v2.gameVersion);
      expect(result.value.prisonId).toBe(v2.prisonId);
      expect(result.value.revision).toBe(v2.revision);
      expect(result.value.createdAt).toBe(v2.createdAt);
      expect(result.value.updatedAt).toBe(v2.updatedAt);
    });

    it(`walks a checked-in V1 "${name}" fixture all the way to the current version in one decode, unmodified`, () => {
      // The full path -- V1 -> V2 -> V3 when this test was written, V1 -> V2
      // -> V3 -> V4 since #259 -- driven by the chain rather than by calling
      // any step directly. This is what a player with a save from the first
      // release actually gets, which is why it asserts
      // `SAVE_SCHEMA_VERSION` rather than a literal.
      const before = JSON.stringify(fixture);
      const result = decodeSaveEnvelope(fixture);
      expect(result).toMatchObject({ ok: true, migrated: true });
      if (!result.ok) return;

      expect(result.value.saveSchemaVersion).toBe(SAVE_SCHEMA_VERSION);
      expect(result.value.payload.kernel).toEqual(fixture.payload.kernel);
      expect(result.value.payload.construction).toEqual(fixture.payload.construction);
      // The migration never mutates the fixture object it was handed.
      expect(JSON.stringify(fixture)).toBe(before);
    });
  }

  it('does not invent a simulation or identity section for a save that never had one', () => {
    // Both sections are absent, not empty. An empty `simulation` would assert
    // "this prison had no prisoners, no guards and no incidents"; an empty
    // `identity` would assert "this prison had nobody named". An absent one
    // says "this save predates that state", which is the truth and is what
    // `RestoredScope` reports to the player.
    const result = decodeSaveEnvelope(throughStorage(v2EnvelopeFrom(inProgressFixture)));
    if (!result.ok) throw new Error('the V2 save must migrate for this test to be meaningful');

    expect('simulation' in result.value.payload).toBe(false);
    expect('identity' in result.value.payload).toBe(false);
    expect(Object.keys(result.value.payload).sort()).toEqual(['construction', 'entities', 'kernel', 'world']);
  });

  it('restores a migrated V2 save exactly as V2 behaved, with the untouched subsystems rebuilt empty', () => {
    // The fresh-prison fixture, because the in-progress one's `entities`
    // section declares an 8-slot store and `EntityStore.loadSnapshot` refuses
    // a capacity other than the runtime's own `DEFAULT_PRISONER_CAPACITY`.
    // That is a pre-existing restriction on hand-written fixtures, unchanged
    // by this issue and noted in docs/PERSISTENCE.md.
    const result = decodeSaveEnvelope(throughStorage(v2EnvelopeFrom(freshPrisonFixture)));
    if (!result.ok) throw new Error('the V2 save must migrate for this test to be meaningful');

    const { runtime, scope } = restoreSimulationRuntime(result.value.payload as unknown as SessionSnapshotBundle);
    // The V2 half comes back...
    expect(runtime.kernel.tick).toBe(freshPrisonFixture.payload.kernel.tick);
    expect(runtime.world.snapshot().chunks.length).toBe(freshPrisonFixture.payload.world.chunks.length);
    // ...and nothing is fabricated for the half the save never held.
    expect(runtime.securityGuards.allGuardIds()).toEqual([]);
    expect(runtime.contraband.all()).toEqual([]);
    expect(runtime.incidents.openIncidents()).toEqual([]);
    expect(runtime.navigation.doors.all()).toEqual([]);
    // ...including names: an empty registry, so every row projects no name,
    // which is exactly the state a session that never minted one is in.
    expect(runtime.actorIdentity.size).toBe(0);
    expect(scope.restored.length).toBeGreaterThan(0);
  });

  it('re-checksums the migrated save so it decodes again as a current-version one', () => {
    const migrated = decodeSaveEnvelope(throughStorage(v2EnvelopeFrom(inProgressFixture)));
    if (!migrated.ok) throw new Error('the V2 save must migrate for this test to be meaningful');

    const again = decodeSaveEnvelope(throughStorage(migrated.value));
    expect(again).toMatchObject({ ok: true, migrated: false });
    if (!again.ok) return;
    expect(again.value).toStrictEqual(migrated.value);
    expect(migrated.value.checksum).toBe(computeSaveChecksum(migrated.value.payload as unknown as JsonValue));
  });

  it('recomputes a checksum identical to the stored one, because V2 -> V3 rewrites nothing', () => {
    // Every other migration in this chain changes the payload and therefore
    // its checksum. This one does not, and that is worth pinning: if a future
    // edit makes V2 -> V3 start rewriting the payload, this test says so.
    const v2 = v2EnvelopeFrom(inProgressFixture);
    const v3 = migrateSaveEnvelopeV2ToV3(v2);
    expect(v3.checksum).toBe(v2.checksum);
    expect(v3.payload).toEqual(v2.payload);
  });

  it('still rejects a corrupt V2 save, because the checksum is verified at the version it was written', () => {
    // The ordering #58 established, now across two hops: the stored checksum
    // is checked against the payload as written, at its declared version,
    // before any migration step runs. Verifying after migration instead would
    // call every older save corrupt; letting the recomputed checksum stand in
    // for verification would call every older save intact.
    const tampered = JSON.parse(JSON.stringify(v2EnvelopeFrom(inProgressFixture))) as { payload: { kernel: { tick: number } } };
    tampered.payload.kernel.tick += 1;
    expect(decodeSaveEnvelope(tampered)).toMatchObject({
      ok: false,
      error: { code: 'checksum-mismatch', atVersion: 2 },
    });
  });

  it('rejects a V2 save whose entity ledger is tampered with, rather than migrating it', () => {
    const tampered = JSON.parse(JSON.stringify(v2EnvelopeFrom(inProgressFixture))) as {
      payload: { entities: { generations: [number, number][] } };
    };
    tampered.payload.entities.generations[0]![0] = 9;
    expect(decodeSaveEnvelope(tampered)).toMatchObject({ ok: false, error: { code: 'checksum-mismatch', atVersion: 2 } });
  });

  it('rejects a structurally invalid V2 save at its own version, not at V3', () => {
    const broken = JSON.parse(JSON.stringify(v2EnvelopeFrom(inProgressFixture))) as {
      payload: { entities: { capacity: number } };
    };
    broken.payload.entities.capacity = -1;
    expect(decodeSaveEnvelope(broken)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: 2 } });
  });

  it('rejects a save declaring a version newer than this build understands', () => {
    const future = { ...v2EnvelopeFrom(inProgressFixture), saveSchemaVersion: SAVE_SCHEMA_VERSION + 1 };
    expect(decodeSaveEnvelope(future)).toMatchObject({
      ok: false,
      error: { code: 'unsupported-version', atVersion: SAVE_SCHEMA_VERSION + 1 },
    });
  });
});

describe('the V3 simulation section is validated, not trusted', () => {
  function v3WithSimulation(mutate: (simulation: Record<string, unknown>) => void): unknown {
    const v3 = decodeSaveEnvelope(throughStorage(v2EnvelopeFrom(inProgressFixture)));
    if (!v3.ok) throw new Error('the V2 save must migrate for this test to be meaningful');

    // A minimal but structurally valid `simulation` section, then broken on
    // purpose. Built by hand rather than captured from a runtime, so this
    // tests the schema and not the encoder that feeds it.
    const simulation: Record<string, unknown> = {
      prisoners: {
        components: {
          activeLength: 0,
          sentenceLengthTicks: [],
          priorIncidentsAtIntake: [],
          sentenceEndTick: [],
          riskTier: [],
          classificationGroupIndex: [],
          intakeStage: [],
          needs: { hunger: [], sleep: [], hygiene: [], bladder: [], safety: [], recreation: [] },
          actionIndex: [],
          actionPhase: [],
          phaseStartedAtTick: [],
          needFulfilledLastTick: [],
          tileX: [],
          tileY: [],
        },
        coldState: { accommodationInstanceId: [], currentActionTargetInstanceId: [] },
        roomInstanceDefinitions: [],
        roomInstanceOccupancy: [],
        cellSharingAssessments: [],
      },
      operations: {
        containers: [],
        jobs: [],
        jobWorkers: { workers: [], busy: [] },
        electricity: { type: 'electricity', nodes: [], connections: [], failedNodeIds: [] },
        water: { type: 'water', nodes: [], connections: [], failedNodeIds: [] },
      },
      navigation: { doors: [] },
      // V6's required section (ADR 0113). Hand-built like everything else here,
      // and minimal: the schema requires at least one group with at least one
      // block, because a session in which no group has a timetable is not a
      // state any build can produce. Gaplessness is `RegimeScheduleRegistry`'s
      // rule and not this schema's, which is why one whole-day block is enough
      // to be well-formed here.
      regimeSchedules: [
        {
          classificationGroupId: 'general-population',
          blocks: [{ startTickOfDay: 0, endTickOfDay: 2_400, allowedCategories: ['sleep'] }],
        },
      ],
      security: {
        sectorDefinitions: [],
        sectorControlStates: [],
        guards: { entityStore: { capacity: 0, nextAvailableIndex: 0, maxActiveIndex: -1, generations: [], freeIndices: [], alive: [] }, records: [] },
        schedules: [],
        deployment: { metrics: { deploymentFailures: 0 } },
        patrol: { metrics: { loopsCompletedOnTime: 0, loopsCompletedLate: 0, loopsMissed: 0 } },
      },
      contraband: {
        items: [],
        intelligence: [],
        informants: [],
        confiscations: [],
        searchPolicies: [],
        searchContainerLocations: [],
        search: { queue: [], active: [], metrics: { itemsDiscovered: 0, itemsMissed: 0, searchesCompleted: 0, searchesCancelled: 0 } },
      },
      incidents: {
        log: [],
        sectorRisk: [],
        gangs: { definitions: [], members: [], reputation: [], grudges: [] },
        tunnels: [],
        watchedSectorIds: [],
        trigger: { metrics: { incidentsTriggered: 0, riotsTriggered: 0, retaliationsTriggered: 0 }, sequence: 0 },
        response: { metrics: { incidentsResolved: 0, incidentsLapsed: 0, respondersDispatched: 0, routeFailures: 0 } },
      },
    };
    mutate(simulation);

    const payload = { ...v3.value.payload, simulation };
    return { ...v3.value, payload, checksum: computeSaveChecksum(payload as unknown as JsonValue) };
  }

  /**
   * A minimal, structurally valid `identity` section on top of a migrated V2
   * envelope, then mutated. Built by hand rather than captured from a
   * runtime, so this tests the schema and not the registry that feeds it.
   */
  function v3WithIdentity(mutate: (identity: Record<string, unknown>) => unknown): unknown {
    const v3 = decodeSaveEnvelope(throughStorage(v2EnvelopeFrom(inProgressFixture)));
    if (!v3.ok) throw new Error('the V2 save must migrate for this test to be meaningful');

    const identity = mutate({
      version: 1,
      poolId: 'placeholder',
      entries: [
        { kind: 'prisoner', entityId: 0, givenName: 'Ada', familyName: 'Okafor' },
        { kind: 'staff', entityId: 0, givenName: 'Bo', familyName: 'Lindqvist' },
      ],
    });

    const payload = { ...v3.value.payload, identity };
    return { ...v3.value, payload, checksum: computeSaveChecksum(payload as unknown as JsonValue) };
  }

  it('accepts a well-formed, empty simulation section', () => {
    expect(decodeSaveEnvelope(v3WithSimulation(() => undefined))).toMatchObject({ ok: true, migrated: false });
  });

  it('rejects prisoner component arrays that disagree with each other about how many slots they describe', () => {
    // The one cross-field rule the field schemas cannot express, and the one
    // that would otherwise throw part-way through a restore instead of being
    // reported as a bad save.
    const broken = v3WithSimulation((simulation) => {
      const prisoners = simulation.prisoners as { components: Record<string, unknown> };
      prisoners.components.activeLength = 2;
      prisoners.components.tileX = [1, 2];
      // every other array is still length 0
    });
    expect(decodeSaveEnvelope(broken)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('rejects an unknown key rather than silently dropping it', () => {
    const broken = v3WithSimulation((simulation) => {
      (simulation.navigation as Record<string, unknown>).portals = [];
    });
    expect(decodeSaveEnvelope(broken)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('rejects an out-of-vocabulary enum value', () => {
    const broken = v3WithSimulation((simulation) => {
      (simulation.security as Record<string, unknown>).sectorControlStates = [['sector-a', 'evacuated']];
    });
    expect(decodeSaveEnvelope(broken)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('accepts a well-formed identity section and carries its names through decoding', () => {
    const envelope = v3WithIdentity((identity) => identity);
    const result = decodeSaveEnvelope(envelope);
    expect(result).toMatchObject({ ok: true, migrated: false });
    if (!result.ok) return;
    expect(result.value.payload.identity?.entries).toEqual([
      { kind: 'prisoner', entityId: 0, givenName: 'Ada', familyName: 'Okafor' },
      { kind: 'staff', entityId: 0, givenName: 'Bo', familyName: 'Lindqvist' },
    ]);
  });

  it('accepts a poolId that no longer matches any configured pool, so replacing the pool renames nobody', () => {
    // `ActorIdentityRegistry.loadSnapshot` tolerates this deliberately —
    // stored names are authoritative. A schema check against the current
    // pool would undo that guarantee at the save boundary instead.
    const envelope = v3WithIdentity((identity) => ({ ...identity, poolId: 'retired-pool-from-an-older-build' }));
    expect(decodeSaveEnvelope(envelope)).toMatchObject({ ok: true, migrated: false });
  });

  it('rejects an actor kind outside the declared vocabulary', () => {
    // `kind` is half the registry's key — prisoners and staff live in
    // separate entity stores that both hand out id 0 — so an unrecognised
    // kind is not a value to ignore.
    const envelope = v3WithIdentity((identity) => ({
      ...identity,
      entries: [{ kind: 'visitor', entityId: 0, givenName: 'Ada', familyName: 'Okafor' }],
    }));
    expect(decodeSaveEnvelope(envelope)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('rejects a registry snapshot version this build does not understand, rather than half-reading it', () => {
    // The registry's `version` is its own and independent of
    // `SAVE_SCHEMA_VERSION`; pinning it here means a future registry shape
    // arriving inside a V3 envelope fails at the boundary.
    const envelope = v3WithIdentity((identity) => ({ ...identity, version: 2 }));
    expect(decodeSaveEnvelope(envelope)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('rejects an empty name rather than restoring an actor with a blank label', () => {
    const envelope = v3WithIdentity((identity) => ({
      ...identity,
      entries: [{ kind: 'prisoner', entityId: 0, givenName: '', familyName: 'Okafor' }],
    }));
    expect(decodeSaveEnvelope(envelope)).toMatchObject({ ok: false, error: { code: 'invalid-shape', atVersion: SAVE_SCHEMA_VERSION } });
  });

  it('rejects a tampered simulation section as a checksum mismatch when the checksum is left alone', () => {
    const envelope = v3WithSimulation(() => undefined) as { payload: { simulation: { incidents: { watchedSectorIds: string[] } } } };
    envelope.payload.simulation.incidents.watchedSectorIds.push('sector-a');
    expect(decodeSaveEnvelope(envelope)).toMatchObject({ ok: false, error: { code: 'checksum-mismatch' } });
  });
});
