import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';
import { createRoomTemplateBuildPlan } from '../../src/simulation/construction/room-template-build-plan';
import { chunkCoordinate } from '../../src/simulation/world/coordinates';
import { SparseWorld } from '../../src/simulation/world/sparse-world';
import { WorldRenderView } from '../../src/rendering/world/world-view';
import type { RenderFrame } from '../../src/rendering/feed/render-feed';
import { projectObliqueWorldFrame, type ObliqueSolid } from '../../src/rendering/camera/oblique-world-projection';
import { projectedRectPrism } from '../../src/rendering/camera/oblique-geometry';
import type { ObliqueCameraState } from '../../src/rendering/camera/oblique-projection';
import { parseObliqueModuleCatalog, selectObliqueModuleFrame } from '../../src/rendering/assets/oblique-module-catalog';
import { parseObliqueModuleRegistry } from '../../src/rendering/assets/oblique-module-registry';
import { CLASSROOM_CASES, CLASSROOM_DESK, CLASSROOM_ORIGIN } from '../fixtures/native-classroom-desk-plan';
const publicRoot = new URL('../../public/', import.meta.url);
it.each([0,1] as const)('selects genuine authored-shader teacher desk in the existing separately paid Classroom q%s free slot', turns => {
  const {plan,orders} = createRoomTemplateBuildPlan('classroom-basic',CLASSROOM_ORIGIN,false,2,turns);
  expect([plan.width,plan.height]).toEqual([7,7]);
  expect(plan.objects.map(row => row.buildableId)).toEqual(['bookshelf-wooden','chair-wooden','chair-wooden','chair-wooden','chair-wooden']);
  expect(plan.objects.some(row => row.buildableId === 'desk-wooden')).toBe(false);
  const {desk,deskTiles} = CLASSROOM_CASES[turns];
  expect([desk.x,desk.y]).toEqual(turns === 0 ? [8,5] : [5,8]); expect(deskTiles).toEqual([[desk.x,desk.y],[desk.x+1,desk.y]]);
  expect(CLASSROOM_DESK).toMatchObject({cost:130,orientation:0,width:2,height:1});
  const world = new SparseWorld(16); const chunk = {x:chunkCoordinate(0),y:chunkCoordinate(0)}; world.load(chunk); world.setOwned(chunk,true);
  const room = {instanceId:'room.classroom:5:5',roomCatalogId:'room.classroom',anchorTileX:5,anchorTileY:5,width:5,height:5};
  const owner = 'classroom-individual-desk';
  const input: RenderFrame = {revision:1,world:WorldRenderView.fromSnapshot(world.snapshot()),rooms:[room],actors:[],roomConditions:[],structures:[
    ...orders.filter(row => row.definitionId.includes('chair') || row.definitionId.includes('bookshelf')).map(row => ({id:row.id,definitionId:row.definitionId,tileX:row.location.x,tileY:row.location.y,phase:'built' as const,orientation:row.objectOrientation ?? 0})),
    {id:owner,definitionId:'desk-wooden',tileX:desk.x,tileY:desk.y,phase:'built',orientation:0}]};
  const camera: ObliqueCameraState = {target:{x:7*64,y:7*64},viewport:{width:1920,height:1080},zoom:2,yawRadians:60*Math.PI/180,elevationRadians:40*Math.PI/180};
  const before = JSON.stringify({structures:input.structures,rooms:input.rooms});
  const solid = projectObliqueWorldFrame(input,camera).raised.find((row): row is ObliqueSolid => row.kind !== 'actor' && row.id === owner);
  expect(solid?.assetId).toBe('furniture.classroom.teacher-desk'); if (solid === undefined) throw new Error('Current paid teacher desk absent');
  expect(solid.orientation ?? 0).toBe(0);
  expect(solid.footprint).toEqual(projectedRectPrism(desk.x*64,desk.y*64,128,64,1,camera).footprint);
  const registry = parseObliqueModuleRegistry(JSON.parse(readFileSync(new URL('game-content/oblique-module-registry.v1.json',publicRoot),'utf8')));
  expect(registry.entries.filter(row => row.assetId === solid.assetId)).toEqual([{assetId:'furniture.classroom.teacher-desk',manifest:'/game-content/oblique-furniture-classroom-teacher-desk.v1.json'}]);
  const catalog = parseObliqueModuleCatalog(JSON.parse(readFileSync(new URL('game-content/oblique-furniture-classroom-teacher-desk.v1.json',publicRoot),'utf8')));
  expect(catalog.source).toBe('assets/source/blender/furniture.classroom.teacher-desk.soft-light.blend');
  expect(catalog.sourceSha256).toBe('a879bba0f04a4f8b08a66fb9e607d1d815a7a6c2a8f7cb84c1d20c7c0d26d376');
  const selected = selectObliqueModuleFrame(catalog,{yawRadians:solid.assetYawRadians ?? camera.yawRadians,elevationRadians:camera.elevationRadians});
  expect(selected).toEqual({yawDegrees:60,elevationDegrees:40,image:'/assets/environment/oblique/furniture.classroom.teacher-desk-yaw+60-elev40.5c8ee6a0fc92.png',sha256:'5c8ee6a0fc927377c5e6ea80f92444764d0ba794a25ddd14acafeec79dfa25e7'});
  expect(createHash('sha256').update(readFileSync(new URL(selected.image.slice(1),publicRoot))).digest('hex')).toBe(selected.sha256);
  expect(JSON.stringify({structures:input.structures,rooms:input.rooms})).toBe(before);
});
